version: '3.8'

services:
  user-auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV_FILE=.env
    volumes:
      - .:/app